all_player_info = {
	"Andy":{
	"Ancient": ["A-ct-smoke-from-A-main.mp4","A-donut-smoke-from-A-main.mp4",],
	"Anubis": [],
	"Dust II": [],
	"Inferno": [],
	"Mirage": [],
	"Nuke": [],
	"Vertigo": [],
	},
	"Daniel":{
	"Ancient": [],
	"Anubis": [],
	"Dust II": [],
	"Inferno": [],
	"Mirage": [],
	"Nuke": [],
	"Vertigo": [],
	},
	"Futao":{
	"Ancient": [],
	"Anubis": [],
	"Dust II": [],
	"Inferno": [],
	"Mirage": [],
	"Nuke": [],
	"Vertigo": [],
	},
	"Julian":{
	"Ancient": [],
	"Anubis": ["B-pillar-molly-from-B-main.mp4",],
	"Dust II": [],
	"Inferno": ["B-coffin-smoke-from-banana.mp4",],
	"Mirage": [],
	"Nuke": [],
	"Vertigo": [],
	},
	"Ling":{
	"Ancient": [],
	"Anubis": [],
	"Dust II": [],
	"Inferno": [],
	"Mirage": [],
	"Nuke": [],
	"Vertigo": [],
	},
	}