all_player_info = {
	"Andy":{
	"Ancient": ["A-ct-smoke-from-A-main.mp4","B-short-smoke-from-B-ruins.mp4",],
	"Anubis": ["A-con-smoke-from-A-water.mp4","A-water-flash-from-broken-wall.mp4","bridge-flash-from-ruins.mp4","B-pillar-molly-from-B-main.mp4","A-stairs-flash-from-mid-doors.mp4",],
	"Dust II": ["A-car-molly-from-A-long.mp4","A-long-corner-smoke-from-T-spawn.mp4","A-long-door-smoke-from-under-A.mp4","ct-cross-smoke-from-A-long.mp4","mid-door-smoke-from-T-spawn.mp4",],
	"Inferno": ["A-deep-long-smoke-from-mid.mp4","A-library-smoke-from-mid.mp4","A-long-smoke-from-second-mid.mp4","A-short-flash-from-mid.mp4","B-ct-boost-smoke-from-banana.mp4","B-site-flash-from-banana.mp4",],
	"Mirage": [],
	"Nuke": [],
	"Vertigo": [],
	},
	"Daniel":{
	"Ancient": ["cave-smoke-from-T-spawn.mp4","mid-red-smoke-from-T-spawn.mp4",],
	"Anubis": ["bridge-smoke-from-T-spawn.mp4","bridge-flash-from-ruins.mp4","B-main-flash-from-B-long.mp4","A-stairs-flash-from-mid-doors.mp4","mid-door-molly-from-bridge.mp4",],
	"Dust II": ["mid-flash-from-ct-spawn.mp4","B-window-smoke-from-B-main.mp4","A-site-flash-from-A-short.mp4","A-site-molly-from-A-short.mp4","A-long-corner-smoke-from-T-spawn.mp4",],
	"Inferno": ["A-moto-smoke-from-A-short.mp4","B-ct-smoke-from-banana.mp4","B-newbox-molly-from-banana.mp4","B-site-flash-from-banana.mp4",],
	"Mirage": [],
	"Nuke": [],
	"Vertigo": [],
	},
	"Futao":{
	"Ancient": ["B-long-smoke-from-B-ruins.mp4","mid-flash-from-T-spawn.mp4","elbow-smoke-from-ct-spawn.mp4","A-temple-smoke-from-A-main.mp4",],
	"Anubis": ["A-cake-molly-from-A-water.mp4","A-heaven-smoke-from-A-water.mp4","A-site-flash-from-A-water.mp4","A-water-flash-from-broken-wall.mp4","bridge-flash-from-mid.mp4","bridge-flash-from-ruins.mp4","cave-flash-from-A-upper.mp4",],
	"Dust II": ["A-long-corner-smoke-from-T-spawn.mp4","A-site-flash-from-A-short.mp4","B-default-rollout-from-tunnels.mp4","ct-cross-smoke-from-A-long.mp4","mid-flash-from-ct-spawn.mp4",],
	"Inferno": ["A-long-smoke-from-second-mid.mp4","A-moto-smoke-from-A-short.mp4","A-short-flash-from-mid.mp4","B-ct-smoke-from-banana.mp4","B-newbox-molly-from-banana.mp4","B-site-flash-from-banana.mp4","mid-smoke-from-ct-spawn.mp4",],
	"Mirage": [],
	"Nuke": [],
	"Vertigo": [],
	},
	"Julian":{
	"Ancient": ["A-temple-smoke-from-A-main.mp4","A-donut-smoke-from-A-main.mp4",],
	"Anubis": ["A-water-flash-from-broken-wall.mp4","B-palace-smoke-from-B-main.mp4","B-pillar-molly-from-B-main.mp4","B-site-smoke-from-B-main.mp4","B-cave-smoke-from-B-main.mp4",],
	"Dust II": ["A-long-corner-smoke-from-T-spawn.mp4","A-long-door-smoke-from-under-A.mp4","B-door-smoke-from-B-tunnels.mp4","mid-door-smoke-from-T-spawn.mp4","B-default-rollout-from-tunnels.mp4",],
	"Inferno": [],
	"Mirage": [],
	"Nuke": [],
	"Vertigo": [],
	},
	"Ling":{
	"Ancient": ["mid-red-smoke-from-T-spawn.mp4","mid-flash-from-T-spawn.mp4","elbow-smoke-from-ct-spawn.mp4",],
	"Anubis": ["A-stairs-flash-from-mid-doors.mp4","A-water-flash-from-broken-wall.mp4","B-main-flash-from-B-long.mp4","bridge-flash-from-mid.mp4","bridge-flash-from-ruins.mp4","cave-smoke-from-T-spawn.mp4",],
	"Dust II": ["A-car-molly-from-A-long.mp4","A-long-corner-smoke-from-T-spawn.mp4","A-long-door-smoke-from-under-A.mp4","ct-cross-smoke-from-A-long.mp4","mid-door-smoke-from-T-spawn.mp4",],
	"Inferno": ["mid-smoke-from-ct-spawn.mp4","B-site-flash-from-banana.mp4","A-deep-long-smoke-from-mid.mp4","A-library-smoke-from-mid.mp4","A-short-flash-from-mid.mp4",],
	"Mirage": [],
	"Nuke": [],
	"Vertigo": [],
	},
	}